import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-neutral-900 min-h-screen text-white w-full flex flex-col items-center p-8">
          <div className="flex flex-row justify-between w-full ">
            <Link href={"/"}>
              <span className="text-2xl">FilterPixel</span>
            </Link>
            <button className="bg-white py-2 px-4 text-neutral-900 rounded-lg text-sm">
              Signup
            </button>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
